SIGDESC = {
    1  : "SIGHUP",
    2  : "SIGINT",
    3  : "SIGQUIT",
    4  : "SIGILL",
    5  : "No signal defined",
    6  : "SIGABRT",
    7  : "No signal defined",
    8  : "SIGFPE",
    9  : "SIGKILL",
    10 : "SIGUSR1-10",
    11 : "SIGSEGV",
    12 : "SIGUSR2-12",
    13 : "SIGPIPE",
    14 : "SIGALRM",
    15 : "SIGTERM",
    16 : "SIGUSR1-16",
    17 : "SIGUSR2-17",
}